### ISSUE TITLE
is FakeSwitch state readable?

### ISSUE THREAD

**Issue by JangoBritt** [saxophonedev/homebridge-fakeswitchfs#3]
So I have an idea. I don't know exactly how to run with it, but thought this might be a good starting point.

Currently, HomeKit doesn't support multiple occupancy for Location triggers.

I can use a Location Trigger to set off a scene when I leave the house
My wife can do the same
but we can't use a location trigger to only set off when both of us have left.

The way this can be done is to use a Location Trigger on each iPhone to change the state or variable of something, and then use that value to manage the multi occupancy.

For Example: 
 
When Adam Leaves the house, set AdamHome to OFF
When Mrs. Leaves the house, set MrsHome to OFF
When Adam Arrives Home, set AdamHome to ON
When MRs. Arrives Home, Set MrsHome to ON

When AdamHome = OFF and MrsHome = OFF , switch on Roomba!
When AdamHome = ON, Switch Off (Dock) Roomba
When MrsHome = ON, Switch Off (Dock) Roomba

Can multiple accessories for FakeSwitch be installed on one HomeBridge?

**Comment by saxophonedev** [comment]
Hey! Sorry for the late answer.
Multiple accessories of FakeSwitch can be installed.
The module stores the state of an accessory in the persist folder. The name is the accessory's name combined with _conf.txt

**Comment by saxophonedev** [comment]
Also, I am planning on creating this idea with an also-open source iPhone mobile app.
